eval $(/opt/homebrew/bin/brew shellenv)

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

# rbenv setup
if which rbenv &> /dev/null; then eval "$(rbenv init - zsh)"; fi

# direnv setup
export DIRENV_LOG_FORMAT=""
if which direnv &> /dev/null; then eval "$(direnv hook zsh)"; fi

export REBEL_HOME=/opt/jrebel
export PATH=${REBEL_HOME}/bin:${PATH}

# vi rules
bindkey -v

# Bind ^R to search backwards in command history like bash.
bindkey "^R" history-incremental-search-backward

# Bind space to edit in $EDITOR from command mode.
autoload -z edit-command-line
zle -N edit-command-line
bindkey -M vicmd ' ' edit-command-line

# git prompt custumizations
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM='verbose'

if [ -f "$(brew --prefix)/etc/bash_completion.d/git-prompt.sh" ]; then
  source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
fi

setopt PROMPT_SUBST
GIT_STATUS=$'$(__git_ps1 " (%s)")'
NEWLINE=$'\n'
export PROMPT="%n@%m:%~${GIT_STATUS}${NEWLINE}> "

alias g="git"

autoload -Uz compinit && compinit

alias ldd='otool -L'
alias vimm='vim ~/Library/Application\ Support/MailMate/Resources/KeyBindings/Custom.plist'
alias spd='cd ~/Library/Containers/com.bohemiancoding.sketch/Data/Library/Application\ Support/sketch/Plugins'
alias t='todo.sh'
alias psxc='ps -ef | grep -i "[x]code"'
function fuxc { kill -9 $(ps -ef | grep -i '[x]code' | awk '{ print $2; }') }
alias ls='ls -G'
alias lsid='security find-identity -p codesigning'

# brew aliases
alias bru="brew update && brew outdated"
alias lsl='lsregister -dump'
alias lsk='lsregister -kill -r -domain local -domain system -domain user'
alias b="bundle"
alias be="b exec"
alias bi="b install"
alias biv="b install --path vendor"
alias bu="b update"
alias bake="be rake"
alias r="rails"
alias tml="tmux list-sessions"
alias tma="tmux attach-session"
alias tmc="clear && tmux clear-history"
alias tmk="tmux kill-session"
alias st='tmux rename-window $(basename $(pwd))'
alias tx='tmuxinator'
alias vi=vim

if [ "$(uname)" = "Darwin" ]; then
  alias vim='mvim -v'
fi

# JS
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

PATH=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support:"$PATH"

# Rust
. "$HOME/.cargo/env"

# uv
. "$HOME/.local/bin/env"

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Lazy
alias lg=lazygit
alias ld=lazydocker
