alias ldd='otool -L'
alias vimm='vim ~/Library/Application\ Support/MailMate/Resources/KeyBindings/Custom.plist'
alias spd='cd ~/Library/Containers/com.bohemiancoding.sketch/Data/Library/Application\ Support/sketch/Plugins'
alias t='todo.sh'
alias psxc='ps -ef | grep -i xcode'
